# Set specify config file
#   http://help.houndci.com/configuration/rubocop
rubocop:
  config_file: .rubocop.yml

# Add `rubocop-rspec` as optional plugin
require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
