name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/build-push-action@v2
        with:
          push: false
          tags: tomohiro/fluentular:latest
          cache-from: type=registry,ref=tomohiro/fluentular:latest
