name: Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  rspec:
    runs-on: ubuntu-20.04
    env:
      TZ: Asia/Tokyo
      BUNDLE_WITHOUT: development
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bundle exec rspec

  coveralls:
    needs: rspec
    runs-on: ubuntu-latest
    steps:
    - uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
